<?php

namespace Subbe\WaveApp;

class AccountSubtypeValue
{
    const CASH_AND_BANK = 'CASH_AND_BANK';
    const COST_OF_GOODS_SOLD = 'COST_OF_GOODS_SOLD';
    const CREDIT_CARD = 'CREDIT_CARD';
    const CUSTOMER_PREPAYMENTS_AND_CREDITS = 'CUSTOMER_PREPAYMENTS_AND_CREDITS';
    const DEPRECIATION_AND_AMORTIZATION = 'DEPRECIATION_AND_AMORTIZATION';
    const DISCOUNTS = 'DISCOUNTS';
    const DUE_FOR_PAYROLL = 'DUE_FOR_PAYROLL';
    const DUE_TO_YOU_AND_OTHER_OWNERS = 'DUE_TO_YOU_AND_OTHER_OWNERS';
    const EXPENSE = 'EXPENSE';
    const GAIN_ON_FOREIGN_EXCHANGE = 'GAIN_ON_FOREIGN_EXCHANGE';
    const INCOME = 'INCOME';
    const INVENTORY = 'INVENTORY';
    const LOANS = 'LOANS';
    const LOSS_ON_FOREIGN_EXCHANGE = 'LOSS_ON_FOREIGN_EXCHANGE';
    const MONEY_IN_TRANSIT = 'MONEY_IN_TRANSIT';
    const NON_RETAINED_EARNINGS = 'NON_RETAINED_EARNINGS';
    const OTHER_CURRENT_ASSETS = 'OTHER_CURRENT_ASSETS';
    const OTHER_CURRENT_LIABILITY = 'OTHER_CURRENT_LIABILITY';
    const OTHER_INCOME = 'OTHER_INCOME';
    const OTHER_LONG_TERM_ASSETS = 'OTHER_LONG_TERM_ASSETS';
    const OTHER_LONG_TERM_LIABILITY = 'OTHER_LONG_TERM_LIABILITY';
    const PAYABLE = 'PAYABLE';
    const PAYABLE_BILLS = 'PAYABLE_BILLS';
    const PAYABLE_OTHER = 'PAYABLE_OTHER';
    const PAYMENT_PROCESSING_FEES = 'PAYMENT_PROCESSING_FEES';
    const PAYROLL_EXPENSES = 'PAYROLL_EXPENSES';
    const PROPERTY_PLANT_EQUIPMENT = 'PROPERTY_PLANT_EQUIPMENT';
    const RECEIVABLE = 'RECEIVABLE';
    const RECEIVABLE_INVOICES = 'RECEIVABLE_INVOICES';
    const RECEIVABLE_OTHER = 'RECEIVABLE_OTHER';
    const RETAINED_EARNINGS = 'RETAINED_EARNINGS';
    const SALES_TAX = 'SALES_TAX';
    const TRANSFERS = 'TRANSFERS';
    const UNCATEGORIZED_EXPENSE = 'UNCATEGORIZED_EXPENSE';
    const UNCATEGORIZED_INCOME = 'UNCATEGORIZED_INCOME';
    const VENDOR_PREPAYMENTS_AND_CREDITS = 'VENDOR_PREPAYMENTS_AND_CREDITS';
}
