<?php

namespace Subbe\WaveApp;

class BusinessType
{
    const ARTISTS_PHOTOGRAPHERS_CREATIVE = 'ARTISTS_PHOTOGRAPHERS_CREATIVE';
    const CONSULTANTS_PROFESSIONALS = 'CONSULTANTS_PROFESSIONALS';
    const FINANCE_INSURANCE = 'FINANCE_INSURANCE';
    const HAIR_SPA_AESTHETICS = 'HAIR_SPA_AESTHETICS';
    const MEDICAL_DENTAL_HEALTH_SERVICE = 'MEDICAL_DENTAL_HEALTH_SERVICE';
    const NONPROFIT_ASSOCIATIONS_GROUPS = 'NONPROFIT_ASSOCIATIONS_GROUPS';
    const PRODUCT_PROVIDER = 'PRODUCT_PROVIDER';
    const REALESTATE_HOME = 'REALESTATE_HOME';
    const RETAILERS_AND_RESELLERS = 'RETAILERS_AND_RESELLERS';
    const SERVICE_PROVIDER = 'SERVICE_PROVIDER';
    const WEB_MEDIA_FREELANCER = 'WEB_MEDIA_FREELANCER';
}
