<?php

namespace Subbe\WaveApp;

class InvoiceSort
{
    const AMOUNT_DUE_ASC = 'AMOUNT_DUE_ASC';
    const AMOUNT_DUE_DESC = 'AMOUNT_DUE_DESC';
    const AMOUNT_PAID_ASC = 'AMOUNT_PAID_ASC';
    const AMOUNT_PAID_DESC = 'AMOUNT_PAID_DESC';
    const CREATED_AT_ASC = 'CREATED_AT_ASC';
    const CREATED_AT_DESC = 'CREATED_AT_DESC';
    const CUSTOMER_NAME_ASC = 'CUSTOMER_NAME_ASC';
    const CUSTOMER_NAME_DESC = 'CUSTOMER_NAME_DESC';
    const DUE_AT_ASC = 'DUE_AT_ASC';
    const DUE_AT_DESC = 'DUE_AT_DESC';
    const INVOICE_DATE_ASC = 'INVOICE_DATE_ASC';
    const INVOICE_DATE_DESC = 'INVOICE_DATE_DESC';
    const INVOICE_NUMBER_ASC = 'INVOICE_NUMBER_ASC';
    const INVOICE_NUMBER_DESC = 'INVOICE_NUMBER_DESC';
    const MODIFIED_AT_ASC = 'MODIFIED_AT_ASC';
    const MODIFIED_AT_DESC = 'MODIFIED_AT_DESC';
    const STATUS_ASC = 'STATUS_ASC';
    const STATUS_DESC = 'STATUS_DESC';
    const TOTAL_ASC = 'TOTAL_ASC';
    const TOTAL_DESC = 'TOTAL_DESC';
}
